services:
#    attribute.example:
#        class: AttributeBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    attribute.attribute_value:
        class: gbenitez\Bundle\AttributeBundle\Form\Type\AttributeValueType
        arguments:
            - @=service('doctrine.orm.entity_manager').getRepository('AttributeBundle:Attribute')
            - @doctrine.orm.entity_manager
        tags:
            - { name: form.type, alias: attribute_value }

    attribute.attributes:
        class: gbenitez\Bundle\AttributeBundle\Form\Type\AttributesType
        tags:
            - { name: form.type, alias: attributes }

    attribute.repository:
        class: gbenitez\Bundle\AttributeBundle\Entity\Repository\AttributeRepository
        factory: [@doctrine.orm.entity_manager, getRepository]
        arguments: [AttributeBundle:Attribute]

    attribute.yaml:
        class: gbenitez\Bundle\AttributeBundle\Form\Type\YamlType
        tags:
            - { name: form.type, alias: yaml }

    attribute.manager:
        class: gbenitez\Bundle\AttributeBundle\Model\AttributeManager
        arguments:
            - @doctrine.orm.entity_manager